version: "3.9"
services:
  rabbitmq:
    image: "rabbitmq:3.11-management"
    ports:
      - "5672:5672"
      - "15672:15672"
  postgres:
    image: "postgres:15.2-alpine3.17"
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
  pgadmin:
    image: "dpage/pgadmin4:7.1"
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@mail.com
      - PGADMIN_DEFAULT_PASSWORD=test1234
  redis:
    image: "redis/redis-stack-server:6.2.6-v7"
    ports:
      - "6379:6379"