apiVersion: v1
kind: Secret
metadata:
  name: reddit-user
type: Opaque
stringData:
  username: guest
  password: guest
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: replicator-hare
spec:
  tags:
  - administrator
  rabbitmqClusterReference:
    name: reddit-cluster
  importCredentialsSecret:
    name: reddit-user
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: sim.default.all
spec:
  vhost: "/"
  userReference:
    name: replicator-hare
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: reddit-cluster