apiVersion: batch/v1
kind: CronJob
metadata:
  name: reddit-api-fetcher
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: reddit-api-fetcher
            image: ptisma/reddit-api-processor:latest
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure