name: Reusable workflow for building and pushing Docker image to Docker Hub repository

on:
  workflow_call:
    inputs:
      contextPath:
        required: true
        type: string
      dockerfilePath:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD :
        required: true

jobs:
  BuildAndPushImage:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.contextPath }}
          file: ${{ inputs.dockerfilePath }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/api-server:latest
          build-args: |
            progress=plain