name: Push
run-name: ${{ github.actor }} is creating push on main 🚀
on:
  push:
    branches:
      - 'main'
jobs:
  IdentifyFolderChanges:
    uses: ./.github/workflows/identify-folder-changes.yml
  
  ApiServer:
    runs-on: ubuntu-latest
    needs: IdentifyFolderChanges
    if: ${{ needs.IdentifyFolderChanges.outputs.api-server == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - run: ls -l
      - run: ls -l
        working-directory: ./api-server
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./api-server/
          file: ./api-server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/api-server:latest
          build-args: |
            progress=plain
            no-cache
      
