name: Push
run-name: ${{ github.actor }} is creating push on main 🚀
on:
  push:
    branches:
      - 'main'

jobs:
  IdentifyFolderChanges:
    uses: ./.github/workflows/identify-folder-changes.yml
    permissions: read-all
  ApiServer:
    needs: IdentifyFolderChanges
    if: ${{ needs.IdentifyFolderChanges.outputs.api-server == 'true' }}
    uses: ./.github/workflows/build-and-push-image.yml
    with:
      context-path: ./api-server/
      dockerfile-path: ./api-server/Dockerfile
    secrets: inherit
      
