name: Push
run-name: ${{ github.actor }} is creating push on main 🚀
on:
  push:
    branches:
      - 'main'
jobs:
  IdentifyFolderChanges:
    # Required permissions
    permissions: read-all
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      api-server: ${{ steps.filter.outputs.api-server }}
      reddit-api-fetcher : ${{ steps.filter.outputs.reddit-api-fetcher }}
      reddit-api-processor: ${{ steps.filter.outputs.reddit-api-processor }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            api-server:
              - 'api-server/**'
            reddit-api-fetcher:
              - 'reddit-api/reddit-api-fetcher/**'
            reddit-api-processor:
              - 'reddit-api/reddit-api-processor/**'
  
  ApiServer:
    steps:
      - uses: actions/checkout@v3
