name: Pull request
run-name: ${{ github.actor }} is creating pull request on main 🚀
on:
  pull_request:
    types:
      - opened
    branches:
      - 'main/**' 

jobs:
  IdentifyFolderChanges:
    uses: ./.github/workflows/identify-folder-changes.yml
    permissions: read-all
  ApiServer:
    needs: IdentifyFolderChanges
    if: ${{ needs.IdentifyFolderChanges.outputs.api-server == 'true' }}
    uses: ./.github/workflows/go-app.yml
    permissions: read-all
    with:
      path: ./api-server/
  
      
